FROM reg.docker.alibaba-inc.com/jdk:1.8.0_66
COPY start.sh /data/start.sh
COPY target/pacman-example-1.0-SNAPSHOT-jar-with-dependencies.jar /data/pacman-example-1.0-SNAPSHOT-jar-with-dependencies.jar
