FROM reg.docker.alibaba-inc.com/jdk:1.8.0_66
COPY start.sh /data/start.sh
COPY src/main/resources/config /data/config
COPY target/pacman-1.0-SNAPSHOT-jar-with-dependencies.jar /data/pacman-1.0-SNAPSHOT-jar-with-dependencies.jar
COPY src/main/resources/map1.txt /data/map1.txt
